"""cascade delete on stacks workspaceId

Revision ID: cb15caa62d8e
Revises: e87e6e84abb8
Create Date: 2022-07-30 17:46:21.748278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb15caa62d8e'
down_revision = 'e87e6e84abb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stacks_workspaceId_fkey', 'stacks', type_='foreignkey')
    op.create_foreign_key(None, 'stacks', 'workspaces', ['workspaceId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stacks', type_='foreignkey')
    op.create_foreign_key('stacks_workspaceId_fkey', 'stacks', 'workspaces', ['workspaceId'], ['id'])
    # ### end Alembic commands ###
