"""added workspaceId to stacks table

Revision ID: e87e6e84abb8
Revises: 0041cc5b625c
Create Date: 2022-07-22 18:45:00.570701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e87e6e84abb8'
down_revision = '0041cc5b625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stacks', sa.Column('workspaceId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stacks', 'workspaces', ['workspaceId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stacks', type_='foreignkey')
    op.drop_column('stacks', 'workspaceId')
    # ### end Alembic commands ###
